/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiscosRouteImport } from './routes/riscos'
import { Route as PlanosDeAcaoRouteImport } from './routes/planos-de-acao'
import { Route as NaoConformidadesRouteImport } from './routes/nao-conformidades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as AuditoriasRouteImport } from './routes/auditorias'
import { Route as IndexRouteImport } from './routes/index'

const RiscosRoute = RiscosRouteImport.update({
  id: '/riscos',
  path: '/riscos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosDeAcaoRoute = PlanosDeAcaoRouteImport.update({
  id: '/planos-de-acao',
  path: '/planos-de-acao',
  getParentRoute: () => rootRouteImport,
} as any)
const NaoConformidadesRoute = NaoConformidadesRouteImport.update({
  id: '/nao-conformidades',
  path: '/nao-conformidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriasRoute = AuditoriasRouteImport.update({
  id: '/auditorias',
  path: '/auditorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditorias': typeof AuditoriasRoute
  '/documentos': typeof DocumentosRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/nao-conformidades': typeof NaoConformidadesRoute
  '/planos-de-acao': typeof PlanosDeAcaoRoute
  '/riscos': typeof RiscosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditorias': typeof AuditoriasRoute
  '/documentos': typeof DocumentosRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/nao-conformidades': typeof NaoConformidadesRoute
  '/planos-de-acao': typeof PlanosDeAcaoRoute
  '/riscos': typeof RiscosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditorias': typeof AuditoriasRoute
  '/documentos': typeof DocumentosRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/nao-conformidades': typeof NaoConformidadesRoute
  '/planos-de-acao': typeof PlanosDeAcaoRoute
  '/riscos': typeof RiscosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditorias'
    | '/documentos'
    | '/indicadores'
    | '/login'
    | '/nao-conformidades'
    | '/planos-de-acao'
    | '/riscos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditorias'
    | '/documentos'
    | '/indicadores'
    | '/login'
    | '/nao-conformidades'
    | '/planos-de-acao'
    | '/riscos'
  id:
    | '__root__'
    | '/'
    | '/auditorias'
    | '/documentos'
    | '/indicadores'
    | '/login'
    | '/nao-conformidades'
    | '/planos-de-acao'
    | '/riscos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriasRoute: typeof AuditoriasRoute
  DocumentosRoute: typeof DocumentosRoute
  IndicadoresRoute: typeof IndicadoresRoute
  LoginRoute: typeof LoginRoute
  NaoConformidadesRoute: typeof NaoConformidadesRoute
  PlanosDeAcaoRoute: typeof PlanosDeAcaoRoute
  RiscosRoute: typeof RiscosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/riscos': {
      id: '/riscos'
      path: '/riscos'
      fullPath: '/riscos'
      preLoaderRoute: typeof RiscosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos-de-acao': {
      id: '/planos-de-acao'
      path: '/planos-de-acao'
      fullPath: '/planos-de-acao'
      preLoaderRoute: typeof PlanosDeAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nao-conformidades': {
      id: '/nao-conformidades'
      path: '/nao-conformidades'
      fullPath: '/nao-conformidades'
      preLoaderRoute: typeof NaoConformidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditorias': {
      id: '/auditorias'
      path: '/auditorias'
      fullPath: '/auditorias'
      preLoaderRoute: typeof AuditoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriasRoute: AuditoriasRoute,
  DocumentosRoute: DocumentosRoute,
  IndicadoresRoute: IndicadoresRoute,
  LoginRoute: LoginRoute,
  NaoConformidadesRoute: NaoConformidadesRoute,
  PlanosDeAcaoRoute: PlanosDeAcaoRoute,
  RiscosRoute: RiscosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
